In [1]:
import numpy as np

In [7]:
# NumPy does element-wise arithmetic and logical operations on arrays of the same shape.

a1 = np.array([1,2,3])
a2 = np.array([10,20,30])

# arithmetics
print(a1+a2)
print(a1*a2)
print(a1-a2)
print(a1/a2)

# unary ops
print(np.square(a1))
print(np.sqrt(a2))

# comparison
print(a1>2)

[11 22 33]
[10 40 90]
[ -9 -18 -27]
[0.1 0.1 0.1]
[1 4 9]
[3.16227766 4.47213595 5.47722558]
[False False  True]


In [8]:
# aggregations

# 1D array
print(np.sum(a1))
print(np.mean(a1))
print(np.std(a1))
print(np.var(a1))

# 2D array
a3 = np.array([[1,2,3],[4,5,6]])
print(np.sum(a3, axis=0)) # sum columns
print(np.sum(a3, axis=1)) # sum rows
print(np.mean(a3, axis=0)) # columns mean

6
2.0
0.816496580927726
0.6666666666666666
[5 7 9]
[ 6 15]
[2.5 3.5 4.5]


In [9]:
# axis logic

# axis = 0: operate down columns, reduce rows. (collapses rows, keeping columns.)
# axis = 1: operate across rows, reduce columns. (collapses columns, keeping rows.)

a4 = np.array([[1,2,3],
               [4,5,6]])
print(np.sum(a4, axis=0))
print(np.sum(a4, axis=1))

[5 7 9]
[ 6 15]


In [13]:
# NaN-safe functions

# when arrays contain NaN, use nan-functions
a5 = np.array([1, np.nan,3,4])
print(np.sum(a5))
print(np.nansum(a5))
print(np.nanmean(a5))
print(np.nanstd(a5))

nan
8.0
2.6666666666666665
1.247219128924647


In [34]:
# compute stats per subject and per condition

# suppose data is subjects x conditions:
data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

# mean per subject
print(np.mean(data, axis=1))

# mean per condition
print(np.mean(data, axis=0))

[2. 5. 8.]
[4. 5. 6.]


In [35]:
# compare manual aggregation and NumPy

# manual row sum
row_sums = []
for row in data:
    row_sum = 0
    for val in row:
        row_sum += val
    row_sums.append(row_sum)

print(row_sums)

# NumPy row sum
print(np.sum(data, axis=1))

# manual mean of columns
col_means = []
for col_indx in range(data.shape[1]):
    col = data[:,col_indx]
    col_mean = sum(col)/len(col)
    col_means.append(col_mean)

print(col_means)

# NumPy mean of columns
print(np.mean(data, axis=0))

[np.int64(6), np.int64(15), np.int64(24)]
[ 6 15 24]
[np.float64(4.0), np.float64(5.0), np.float64(6.0)]
[4. 5. 6.]
