# NumPy Element-wise Operations and Aggregations

In [3]:
import numpy as np

In [4]:
# NumPy does element-wise arithmetic and logical operations on arrays of the same shape.

a1 = np.array([1,2,3])
a2 = np.array([10,20,30])

# arithmetics
print(a1+a2)
print(a1*a2)
print(a1-a2)
print(a1/a2)

# unary ops
print(np.square(a1))
print(np.sqrt(a2))

# comparison
print(a1>2)

[11 22 33]
[10 40 90]
[ -9 -18 -27]
[0.1 0.1 0.1]
[1 4 9]
[3.16227766 4.47213595 5.47722558]
[False False  True]


In [5]:
# Aggregations

# 1D array
print(np.sum(a1))
print(np.mean(a1))
print(np.std(a1))
print(np.var(a1))

# 2D array
a3 = np.array([[1,2,3],[4,5,6]])
print(np.sum(a3, axis=0)) # sum columns
print(np.sum(a3, axis=1)) # sum rows
print(np.mean(a3, axis=0)) # columns mean

6
2.0
0.816496580927726
0.6666666666666666
[5 7 9]
[ 6 15]
[2.5 3.5 4.5]


Axis logic
- Axis = 0: operate down columns, reduce rows. (collapses rows, keeping columns.)
- Axis = 1: operate across rows, reduce columns. (collapses columns, keeping rows.)

In [6]:
a4 = np.array([[1,2,3],
               [4,5,6]])
print(np.sum(a4, axis=0))
print(np.sum(a4, axis=1))

[5 7 9]
[ 6 15]


In [7]:
# NaN-safe functions

# When arrays contain NaN, use nan-functions
a5 = np.array([1, np.nan,3,4])
print(np.sum(a5))
print(np.nansum(a5))
print(np.nanmean(a5))
print(np.nanstd(a5))

nan
8.0
2.6666666666666665
1.247219128924647


In [8]:
# Compute stats per subject and per condition

# Suppose data is subjects x conditions:
data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

# Mean per subject
print(np.mean(data, axis=1))

# Mean per condition
print(np.mean(data, axis=0))

[2. 5. 8.]
[4. 5. 6.]


In [10]:
# Compare manual aggregation and NumPy

# Manual row sum
row_sums = []
for row in data:
    row_sum = 0
    for val in row:
        row_sum += val
    row_sums.append(row_sum)

print("Row sum: ", row_sums)

# NumPy row sum
print("NumPy row sum: ", np.sum(data, axis=1))

# Manual mean of columns
col_means = []
for col_indx in range(data.shape[1]):
    col = data[:,col_indx]
    col_mean = sum(col)/len(col)
    col_means.append(col_mean)

print("Column mean: ", col_means)

# NumPy mean of columns
print("NumPy mean of columns: ", np.mean(data, axis=0))

Row sum:  [np.int64(6), np.int64(15), np.int64(24)]
NumPy row sum:  [ 6 15 24]
Column mean:  [np.float64(4.0), np.float64(5.0), np.float64(6.0)]
NumPy mean of columns:  [4. 5. 6.]
